main: torben.smp.main
version: 1.0
name: SMP Plugin
api-version: 1.13

commands:
  template:
    description: Main command for TemplatePlugin. Use /template help for more info
  rulebook:
    description: gives you the rule book
  infobook:
    description: gives you the info book
permissions:
  template.user:
    description: Allows player to use the plugin's user shit :)
    default: true
  template.admin:
    description: Allows player to use the plugin's admin shit
    default: op
  smp.user:
    description: Allows player to use the SMP plugin shit and stuff
    default: true